services:
  - type: web
    name: kktix-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: LINE_TOKEN
        sync: false
      - key: LINE_GROUP_ID
        sync: false
      - key: KKTIX_URL
        sync: false

  - type: cron
      name: kktix-scheduler
      env: python
      schedule: "*/1 * * * *"  # 每 1 分鐘
      buildCommand: pip install -r requirements.txt
      startCommand: python worker.py
