name: KKTIX Check Every 5 Min

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-kktix:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render /check
        run: curl -s https://kktix-line-bot.onrender.com/check
